### PR TITLE
fix(ObjectCreatorPage): Fix bug where has_many/many_many components wouldn't use "Stage" copy of records when editing.

### PR DESCRIPTION
**Pull request by silbinarywolf**
fix(ObjectCreatorPage): Fix bug where has_many/many_many components wouldn't use "Stage" copy of records when editing.

### CODE REVIEW

**Comment by nyeholt** [comment]
I get why it needs to be this way - however are there any issues with later-executing code that expects things to be back on Live again ?

**Comment by silbinarywolf** [comment]
The thought crossed my mind... and I'm not sure. 
I can't imagine a case where it expects a Live object.

**Comment by nyeholt** [comment]
I mean more so that subsequent parts of the request execution; eg are other objects loaded, or templates rendered, that may now be in Stage mode?

**Comment by silbinarywolf** [comment]
It's hard to know that because of the complexity / multiple forking codepaths this can go down. 

As I said, thought crossed my mind but looking over the code I don't see anything where the module itself might expect a Live object that causes different behaviour. It does go out to user-code in various places so in those instances, perhaps the module might do something the user didn't expect.

**Comment by nyeholt** [comment]
All good, will keep it back of mind

**Comment by silbinarywolf** [comment]
SS 4.0 will resolve this issue:
https://github.com/silverstripe/silverstripe-framework/issues/6680#issuecomment-286276932

**Pull request merged**
